In [2]:
import json
import pandas as pd
import reverse_geocoder as rg

In [3]:
# We point to the specific CSV file
societies = pd.read_csv('D-PLACE-dplace-cldf-908f302/cldf/societies.csv')

# This shows us the column names and the first 5 rows
societies.tail(10)

,ID,Name,Latitude,Longitude,Glottocode,Name_and_ID_in_source,xd_id,alt_names_by_society,main_focal_year,HRAF_name_ID,HRAF_ID,origLat,origLong,comment,glottocode_comment,region,type,Language_Level_Glottocodes,ISO639P3code,Contribution_ID
6674,zhang_et_al2019_Trung_Nujiang_Nungish,Trung_Nujiang_Nungish,28.00792,98.49449,drun1238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6675,zhang_et_al2019_Xumi_Naic,Xumi_Naic,28.38950,100.40000,shix1238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6676,zhang_et_al2019_Yi_Dafang_Ngwi,Yi_Dafang_Ngwi,25.77070,102.36700,wusa1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6677,zhang_et_al2019_Yi_Mile_Ngwi,Yi_Mile_Ngwi,24.60090,103.71300,axiy1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6678,zhang_et_al2019_Yi_Mojiang_Ngwi,Yi_Mojiang_Ngwi,23.05800,101.41200,sout2723,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6679,zhang_et_al2019_Yi_Nanjian_Ngwi,Yi_Nanjian_Ngwi,24.87090,100.71100,xish1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6680,zhang_et_al2019_Yi_Sani_Ngwi,Yi_Sani_Ngwi,24.27800,103.75900,sani1269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6681,zhang_et_al2019_Yi_Weishan_Ngwi,Yi_Weishan_Ngwi,24.87090,100.71100,xish1235,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6682,zhang_et_al2019_Yi_Wuding_Ngwi,Yi_Wuding_Ngwi,25.48000,102.48000,wudi1238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019
6683,zhang_et_al2019_Zeme_Naga,Zeme_Naga,25.34990,93.64630,zeme1240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,languoid,NaN,NaN,dplace-phylogeny-zhang_et_al2019

In [4]:
societies.shape

(6684, 20)

In [5]:
# i want to see the best way to filter the region into a continent

region_group = societies.groupby('region').count()['ID']
region_group

region
Arabian Peninsula                 3
Australia                       100
Brazil                           73
Caribbean                        16
Caucasus                         16
Central America                  27
China                            26
East Tropical Africa             97
Eastern Asia                     31
Eastern Canada                   37
Eastern Europe                   33
Indian Subcontinent             104
Indo-China                       43
Macaronesia                       1
Malesia                          88
Mexico                           57
Middle Asia                      10
Middle Europe                    14
Mongolia                          2
New Zealand                       4
North-Central Pacific             3
North-Central U.S.A.             39
Northeast Tropical Africa       114
Northeastern U.S.A.              21
Northern Africa                  39
Northern Europe                  21
Northern South America           47
Northwestern Pacific             27
Northwestern U.S.A.             138
Papuasia                         95
Russian Far East                 20
Siberia                          20
South Tropical Africa            65
South-Central Pacific            14
South-Central U.S.A.             48
Southeastern Europe              31
Southeastern U.S.A.              19
Southern Africa                  47
Southern South America           40
Southwestern Europe              13
Southwestern Pacific             46
Southwestern U.S.A.             260
Subantarctic Islands              1
Subarctic America                82
West Tropical Africa            204
West-Central Tropical Africa    141
Western Asia                     39
Western Canada                  106
Western Indian Ocean             11
Western South America            66
Name: ID, dtype: int64

In [6]:
region_group.sum()
#concerning that we started with over 6 thousand and now have ~2600 with region, maybe using long/lat is a better way?

np.int64(2599)

In [ ]:
counter = 0
geo_dat = []
for i in range(0, 6684):
    geo_dat.append(rg.search((societies['Latitude'].iloc[counter], societies['Longitude'].iloc[counter])))
    counter += 1

In [13]:
geo_dat_cleaned = [x[0] for x in geo_dat]

In [15]:
geo_dat_cleaned

[{'lat': '-19.66667',
  'lon': '22.26667',
  'name': 'Nokaneng',
  'admin1': '',
  'admin2': '',
  'cc': 'BW'},
 {'lat': '60.79222',
  'lon': '-161.75583',
  'name': 'Bethel',
  'admin1': 'Alaska',
  'admin2': 'Bethel Census Area',
  'cc': 'US'},
 {'lat': '49.48062',
  'lon': '-119.58584',
  'name': 'Penticton',
  'admin1': 'British Columbia',
  'admin2': '',
  'cc': 'CA'},
 {'lat': '50.63955',
  'lon': '-93.23526',
  'name': 'Ear Falls',
  'admin1': 'Ontario',
  'admin2': '',
  'cc': 'CA'},
 {'lat': '49.68351',
  'lon': '-83.66654',
  'name': 'Hearst',
  'admin1': 'Ontario',
  'admin2': '',
  'cc': 'CA'},
 {'lat': '49.05018',
  'lon': '-76.98273',
  'name': 'Lebel-sur-Quevillon',
  'admin1': 'Quebec',
  'admin2': 'Nord-du-Quebec',
  'cc': 'CA'},
 {'lat': '50.63955',
  'lon': '-93.23526',
  'name': 'Ear Falls',
  'admin1': 'Ontario',
  'admin2': '',
  'cc': 'CA'},
 {'lat': '65.28201',
  'lon': '-126.8329',
  'name': 'Norman Wells',
  'admin1': 'Northwest Territories',
  'admin2': '',
  'cc': 'CA'},
 {'lat': '64.06013',
  'lon': '-139.43328',
  'name': 'Dawson City',
  'admin1': 'Yukon',
  'admin2': '',
  'cc': 'CA'},
 {'lat': '65.28201',
  'lon': '-126.8329',
  'name': 'Norman Wells',
  'admin1': 'Northwest Territories',
  'admin2': '',
  'cc': 'CA'}]

In [17]:
geoDF = pd.DataFrame(geo_dat_cleaned)

geoDF.head()

         lat         lon       name            admin1              admin2  cc
0  -19.66667    22.26667   Nokaneng                                        BW
1   60.79222  -161.75583     Bethel            Alaska  Bethel Census Area  US
2   49.48062  -119.58584  Penticton  British Columbia                      CA
3   50.63955   -93.23526  Ear Falls           Ontario                      CA
4   49.68351   -83.66654     Hearst           Ontario                      CA

In [7]:
coordinates = list(zip(societies['Latitude'],societies['Longitude']))
results = rg.search(coordinates) # This is vectorized and much faster
societies['Country_Code'] = [r['cc'] for r in results]
#i got 6 errors in worker process at first when just trying to talke long,lat and get coordinates
# so I'm adding a filter to hopefully fix that, im thinking a few entries don't have them

Loading formatted geocoded file...

RuntimeError: 6 errors in worker processes

In [10]:
rg.search((111.0233,84.2343))

[{'lat': '73.50819',
  'lon': '80.52918',
  'name': 'Dikson',
  'admin1': 'Krasnoyarskiy',
  'admin2': '',
  'cc': 'RU'}]